#!/usr/bin/env bash 

if [ "$USER" != "root" ]
then
  echo "ERROR: Run as root"
  exit 1
fi  
 
/usr/local/emhttp/plugins/dynamix.cache.dirs/scripts/rc.cachedirs stop

#   [ -x /usr/local/emhttp/plugins/dynamix.cache.dirs/scripts/rc.cachedirs ] && 
#   /usr/local/emhttp/plugins/dynamix.cache.dirs/scripts/rc.cachedirs stop || 
#   /usr/local/emhttp/plugins/dynamix.cache.dirs/scripts/cache_dirs -q
